### ISSUE TITLE
ArrayIndexOutOfBoundsException in io.branch.referral.Branch$BranchWindowCallback.dispatchTouchEvent

### ISSUE THREAD

**Issue by fred8** [BranchMetrics/android-branch-deep-linking#263]
Hey there!
We noticed this crash report in our tracking tool (stack trace below).
I wonder if you have any fixes for that problem, it happens quite often.

Thank you for your support,
Cheers,

Fred

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
       at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
       at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
       at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2839)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2514)
       at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2831)
```

**Comment by sojanpr** [comment]
@fred8 Sorry that you are seeing this issue. We had a fix for this issue long back . We have removed the Branch Window call back from the sdk earlier this year. Could you please check your SDK version and update the SDK version (the latest is 1.14.3)
