### ISSUE TITLE
NPE in BranchStrongMatchHelper$2

### ISSUE THREAD

**Issue by Jeff11** [BranchMetrics/android-branch-deep-linking#306]
Hi guys,

I've noticed a crash in this class, maybe you want to check that :)

Here's the stacktrace:

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.customtabs.CustomTabsSession.a(android.net.Uri, android.os.Bundle, java.util.List)' on a null object reference
       at io.branch.referral.BranchStrongMatchHelper$2.onCustomTabsServiceConnected(SourceFile:64)
       at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(SourceFile:32)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
       at android.os.Handler.handleCallback(Handler.java:746)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5443)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)`

**Comment by aaustin** [comment]
@Jeff11 I'm super sorry you've encountered this. We realized late last night that this was a rare possibilities and have deployed a fix in 2.4.4 (https://github.com/BranchMetrics/android-branch-deep-linking/pull/305). Can upgrade to that version ASAP?

Sincere apologies!

**Comment by aaustin** [comment]
Please re-open if that doesn't resolve it.
