### ISSUE TITLE
java.lang.SecurityException: Need BLUETOOTH permission

### ISSUE THREAD

**Issue by manuel-sejourne** [BranchMetrics/android-branch-deep-linking#343]
Hi ! 

I am faced with an issue after integrating your SDK.

`java.lang.SecurityException: Need BLUETOOTH permission: Neither user 10138 nor current process has android.permission.BLUETOOTH.
                                                                              at android.os.Parcel.readException(Parcel.java:1620)
                                                                              at android.os.Parcel.readException(Parcel.java:1573)
                                                                              at android.bluetooth.IBluetoothManager$Stub$Proxy.registerStateChangeCallback(IBluetoothManager.java:358)
                                                                              at android.bluetooth.BluetoothAdapter.<init>(BluetoothAdapter.java:594)
                                                                              at android.bluetooth.BluetoothAdapter.getDefaultAdapter(BluetoothAdapter.java:576)
                                                                              at io.branch.referral.SystemObserver.getBluetoothPresent(SystemObserver.java:313)
                                                                              at io.branch.referral.DeviceInfo.<init>(DeviceInfo.java:95)
                                                                              at io.branch.referral.DeviceInfo.getInstance(DeviceInfo.java:86)
                                                                              at io.branch.referral.ServerRequest.setPost(ServerRequest.java:141)
                                                                              at io.branch.referral.ServerRequestRegisterOpen.<init>(ServerRequestRegisterOpen.java:60)
                                                                              at io.branch.referral.Branch.initializeSession(Branch.java:2954)
                                                                              at io.branch.referral.Branch.initUserSessionInternal(Branch.java:1089)
                                                                              at io.branch.referral.Branch.initSession(Branch.java:742)
                                                                              at io.branch.referral.Branch.initSessionWithData(Branch.java:863)
                                                                              at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityStarted(Branch.java:3044)
                                                                              at android.app.Application.dispatchActivityStarted(Application.java:229)
                                                                              at android.app.Activity.onStart(Activity.java:1324)`

Is there a way to deactivate this feature ? 

Thanks in advance for your answers

Manuel

**Comment by sojanpr** [comment]
@manuel-sejourne Sorry that you are facing this issue. It seems like you maybe using an old version of SDK we have removed the  bluetooth requirement a while ago. The latest version Branch is 2.4.4.  Could you please  try with that the latest  version
`compile 'io.branch.sdk.android:library:2.+'`
