### ISSUE TITLE
NPE onGAdsFetchFinished 2.5.8 SDK

### ISSUE THREAD

**Issue by krcho** [BranchMetrics/android-branch-deep-linking#401]
new SDK 2.5.8 make NullPointerException 

this is stack trace

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.Context android.app.Activity.getApplicationContext()' on a null object reference
       at io.branch.referral.Branch.performCookieBasedStrongMatch(SourceFile:2277)
       at io.branch.referral.Branch.onGAdsFetchFinished(SourceFile:1409)
       at io.branch.referral.SystemObserver$GAdsPrefetchTask.onPostExecute(SourceFile:631)
       at io.branch.referral.SystemObserver$GAdsPrefetchTask.onPostExecute(SourceFile:595)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by EvangelosG** [comment]
Hi @krcho -- thanks for the crash report! Do you have steps to reproduce?

**Comment by EvangelosG** [comment]
Hi @krcho -- in addition to my previous ask (steps to reproduce) may you please try this branch to see if it resolves your issue? https://github.com/BranchMetrics/android-branch-deep-linking/pull/402 -- Let me know!

**Comment by krcho** [comment]
good 
I'll check your issue #402 
Thank you for fast fix
