### ISSUE TITLE
please fix this as soon as possible 

### ISSUE THREAD

**Issue by myinnos** [BranchMetrics/android-branch-deep-linking#406]
around 600 users effected with this issue 

SDK version : almost all types from 4.4 to 7.0

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.support.customtabs.CustomTabsSession.mayLaunchUrl(android.net.Uri, android.os.Bundle, java.util.List)' on a null object reference
at io.branch.referral.BranchStrongMatchHelper$2.onCustomTabsServiceConnected(BranchStrongMatchHelper.java:64)
at android.support.customtabs.CustomTabsServiceConnection.onServiceConnected(CustomTabsServiceConnection.java:32)
at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1223)
at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1240)
at android.os.Handler.handleCallback(Handler.java:746)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5443)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

**Comment by EvangelosG** [comment]
Hi @myinnos -- thanks for bringing this to our attention. I see you also e-mailed our support portal, let's work through the issue there and I'll report our findings here for others.

**Comment by sojanpr** [comment]
@myinnos We are sorry that you are  facing this issue .  We have fixed this issue in v2.4.4.
Could you please make sure you are using  the version above this

**Comment by myinnos** [comment]
@EvangelosG @sojanpr 
Thank you for your effort! 

**Current gradle details** 
Branch version - `2.4.3`
CustomTabs version - `25.2.0`
Crashlytics version -  `2.6.7`
Fabric version - `1.3.10`
```
minSdkVersion 16
targetSdkVersion 23
```
Now i will upgrade **branch** version to `2.4.4` 👍 

Let me know if i need to do any changes

**Comment by EvangelosG** [comment]
Hi @myinnos -- Please use the latest version, 2.5.9.

**Comment by EvangelosG** [comment]
You can always check here for latest - https://github.com/BranchMetrics/android-branch-deep-linking/releases -- or in your gradle file use the following notation: `compile 'io.branch.sdk.android:library:2.+'`

**Comment by myinnos** [comment]
@EvangelosG Thank you 🥇
