### ISSUE TITLE
BadParcelableException when opening links from Facebook

### ISSUE THREAD

**Issue by giperwlad** [BranchMetrics/android-branch-deep-linking#464]
I use Branch SDK 2.10.3. And crash was detected in the Fabric report:

      Fatal Exception: java.lang.RuntimeException: Unable to resume activity {com.reverllc.rever/com.reverllc.rever.ui.splash.SplashActivity}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.facebook.events.common.ActionSource
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3844)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
      Caused by android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.facebook.events.common.ActionSource
       at android.os.Parcel.readParcelableCreator(Parcel.java:2545)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2374)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:731)
       at android.content.Intent.getBooleanExtra(Intent.java:6616)
       at io.branch.referral.Branch.checkIntentForSessionRestart(Branch.java:2492)
       at io.branch.referral.Branch.access$1000(Branch.java:75)
       at io.branch.referral.Branch$BranchActivityLifeCycleObserver.onActivityResumed(Branch.java:2432)
       at android.app.Application.dispatchActivityResumed(Application.java:240)
       at android.app.Activity.onResume(Activity.java:1332)
       at android.support.v4.app.FragmentActivity.onResume(FragmentActivity.java:485)
       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1277)
       at android.app.Activity.performResume(Activity.java:7103)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3821)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3885)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3051)
       at android.app.ActivityThread.-wrap14(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1642)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Multidex enabled.
And I don't have Facebook event package in my project.
I think crash occurred  after the link is opened from Facebook app, but I could not reproduce it.
Similar problem: http://git.net/ml/general/2014-10/msg39597.html

**Comment by sojanpr** [comment]
@giperwlad We are trying  to reproduce and fix this issue. Will update you shortly. Do you know the version of the Android causing this issue?

**Comment by giperwlad** [comment]
@sojanpr Android versions : 5.0, 5.1.1, 7.0.

**Comment by EvangelosG** [comment]
Hi @giperwlad -- thank you very much for the report! I was able to identify the issue from Chrome itself (https://bugs.chromium.org/p/chromium/issues/detail?id=412527 - the fix: https://chromium.googlesource.com/chromium/src/+/4bca3b37801c502a164536b804879c00aba7d304) and I've created a PR which offers the same protection: https://github.com/BranchMetrics/android-branch-deep-linking/pull/465 -- we'll be testing/releasing this early next week.

**Comment by SAPNA-BHOR** [comment]
hi @EvangelosG did you get the solution? I have integrated FB sdk in my app and getting the same issue as **Andriod: ClassNotFoundException when unmarshalling: com.facebook.events.common.ActionSource**

can you please suggest something?

**Comment by EvangelosG** [comment]
Hi @SAPNA-BHOR -- I created a PR with the fix here: https://github.com/BranchMetrics/android-branch-deep-linking/pull/465 -- we are releasing it this week. I'll make sure update this thread once it goes out! In the meantime if you want to try it now, please build our SDK with the branch "BadParcelableException-fix"

**Comment by sojanpr** [comment]
Another thing you could check is the version of `com.facebook.events.common.ActionSource` you are using with your intent. This looks like a conflict in the way parcel handled in the class in different versions. 
For eg. One version of the above class may be writing an int to parcel and another  version trying to read the same param as String. Are  you using  any Facebook app linking  with your app

**Comment by SAPNA-BHOR** [comment]
@sojanpr  Yes, i am trying to implement deep linking in the app generated from facebook ads.
Now i got it working somehow by adding Try catch in the method where i m trying to retrieve data.
First time it always crashes and when i try to retrieve it second time it gives me proper data.
Problem is that now this works on some of the version of android and not on other versions. Dunno about pattern on which it works.8 am using Face book sdk in the app not the branchmetrics one. But issue is same of BadParcelableException.

Can you suggest something?

**Comment by sojanpr** [comment]
@SAPNA-BHOR  We have opened the PR with some safety mechanism to prevent  this crash. This is under QA and we will be updating it in couple of days (v2.11.2)

**Comment by sojanpr** [comment]
@SAPNA-BHOR We have released v2.12.0 with a safety catch for this. This will prevent the crash but you may have to check the  Facebook SDK version which actually causes the issue

**Comment by seviu** [comment]
It is a missing enum in the facebook android sdk, which can only be handled in the app. I havea 'fix' for it:
https://github.com/seviu/facebook-android-sdk

Basicaly create an enum com.facebook.events.common.ActionSource with the following implementation:

`package com.facebook.events.common;

import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;

public enum ActionSource implements Parcelable {
    UNKNOWN(0),
    PERMALINK(1),
    DASHBOARD(2),
    NEWSFEED(3),
    GROUP(4),
    PAGE(5),
    TIMELINE(22),
    NOTIFICATION(29),
    GRAPH_SEARCH(70),
    LAUNCHER(78),
    PAGE_UPCOMING_EVENTS_CARD(98),
    MOBILE_SUGGESTIONS_DASHBOARD(201),
    MOBILE_SUGGESTIONS_LIST(202),
    MOBILE_EVENT_COMPOSER(203),
    MOBILE_BOOKMARK_TAB(206),
    MOBILE_SYSTEM_NOTIFICATION(207),
    MOBILE_SUBSCRIPTIONS_DASHBOARD(208),
    MOBILE_SUBSCRIPTIONS_LIST(209),
    GUESTS_VIEW(400);

    public static final String ACTION_REF_PARAM = "action_ref";

    private final int mParamValue;

    public static final Creator<ActionSource> CREATOR = new Creator<ActionSource>() {
        @Override
        public ActionSource createFromParcel(Parcel source) {
            String name = source.readString();
            return ActionSource.valueOf(name);
        }

        @Override
        public ActionSource[] newArray(int size) {
            return new ActionSource[0];
        }
    };

    private ActionSource(int i) {
        this.mParamValue = i;
    }

    public int describeContents() {
        return 0;
    }

    public int getParamValue() {
        return this.mParamValue;
    }

    public static void putActionRef(Bundle bundle, ActionSource actionSource) {
        bundle.putParcelable(ACTION_REF_PARAM, actionSource);
    }

    public void writeToParcel(Parcel parcel, int i) {
        String name = name();
        parcel.writeString(name);
    }
}
`

**Comment by sojanpr** [comment]
@seviu Thanks for updating fix for the Facebook SDK.

**Comment by seviu** [comment]
@sojanpr I just tested this on a sample project and it is not needed to have a custom facebook library. Just having this class somewhere (and placing a proguard rule so that it does not get obfuscated) is enough. You can see the ticket here: https://developers.facebook.com/bugs/1858439831138106/
