### ISSUE TITLE
Crash on Android 4.4 (KitKat) - NoClassDefFoundError

### ISSUE THREAD

**Issue by seanadkinson** [BranchMetrics/android-branch-deep-linking#493]
Hi there,

Running on Android 4.4, we get a crash upon starting our app:

```
java.lang.NoClassDefFoundError: io.branch.referral.Branch$CUSTOM_REFERRABLE_SETTINGS
    at io.branch.referral.Branch.<clinit>(Branch.java:357)
    at com.streem.pro.MainApplication.onCreate(MainApplication.java:97)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
    at android.app.ActivityThread.access$1500(ActivityThread.java:135)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.app.ActivityThread.main(ActivityThread.java:5017)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
    at dalvik.system.NativeStart.main(Native Method)
```

Here is the relevant part of MainApplication:

```

    @Override
    public void onCreate() {
        super.onCreate();
        Branch.getAutoInstance(this);
        ...
    }
```

We don't have this crash on newer versions of Android.  I'm still doing some testing to narrow down whether this is just a KitKat issue, or something larger, and will report back with more details.  Have you guys seen this issue before?

**Comment by sojanpr** [comment]
@seanadkinsonmostly this is  caused by the Dex size issue. Please check here 
https://github.com/BranchMetrics/android-branch-deep-linking#classnotfoundexception--branchjava

**Comment by seanadkinson** [comment]
Yes, thank you @sojanpr.  I searched the Issues on github, but not the README.  Apologies for that, but thank you for your time!

**Comment by AhsanAli13503** [comment]
Got this issue how you resolve can anyone tell?

**Comment by AhsanAli13503** [comment]
java.lang.NoClassDefFoundError: 
  at io.branch.rnbranch.RNBranchModule.getAutoInstance (RNBranchModule.java:92)
  at pk.com.mobilink.bizstore.MainApplication.onCreate (MainApplication.java:82)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1014)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4589)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:155)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1303)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5426)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1268)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1084)
  at dalvik.system.NativeStart.main (Native Method)
