### ISSUE TITLE
Crash when calling generateShortUrl from a background thread

### ISSUE THREAD

**Issue by edenman** [BranchMetrics/android-branch-deep-linking#504]
```
Caused by: java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
        at android.os.Handler.<init>(Handler.java:209)
        at android.os.Handler.<init>(Handler.java:123)
        at io.branch.referral.InstallListener.captureInstallReferrer(InstallListener.java:41)
        at io.branch.referral.Branch.registerAppInit(Branch.java:2228)
        at io.branch.referral.Branch.initializeSession(Branch.java:2182)
        at io.branch.referral.Branch.initUserSessionInternal(Branch.java:1232)
        at io.branch.referral.Branch.handleNewRequest(Branch.java:2300)
        at io.branch.referral.Branch.generateShortLinkAsync(Branch.java:2030)
        at io.branch.referral.Branch.generateShortLinkInternal(Branch.java:1955)
        at io.branch.referral.BranchUrlBuilder.generateUrlInternal(BranchUrlBuilder.java:153)
        at io.branch.referral.BranchUrlBuilder.generateUrl(BranchUrlBuilder.java:144)
        at io.branch.referral.BranchShortLinkBuilder.generateShortUrl(BranchShortLinkBuilder.java:140)
        at io.branch.indexing.BranchUniversalObject.generateShortUrl(BranchUniversalObject.java:599)
        at co.recharge.consumer.domain.BranchReferralLinkCreator.generateLink(BranchReferralLinkCreator.kt:25)
...
```
where `BranchReferralLinkCreator.generateLink` is called from the rx `Schedulers.io()` which uses non-main-threads.  I see in #462 you recommend calling `initSession` from the main thread...is that a requirement for `generateShortUrl` as well?  I've only had one instance of this crash so it feels like this is a weird edge case or something.

**Comment by edenman** [comment]
oh, weird.  it looks like `Branch.handleNewRequest` checks the initialization state and only calls `initUserSessionInternal` if it's not initialized.  I'm calling `Branch.getAutoInstance(this)` in my `Application.onCreate` so maybe initialization failed in this case, and that's why it's trying to init when I call `generateShortUrl`?  And then blowing up bc I'm on a background thread?

**Comment by edenman** [comment]
I should mention, this is on `2.12.1` and the device that had the crash was running android `5.0.1`.  I have since upgraded to Branch `2.13.1`, just haven't released yet.

**Comment by sojanpr** [comment]
@edenman the `generateShortUrl` method internally execute on a background thread ( using  `AsyncTask#doInBackground()` ) . Thats why you are getting the above issue when calling from a background thread. Looks like it is the same as the below issue
https://github.com/BranchMetrics/android-branch-deep-linking/pull/273

**Comment by edenman** [comment]
Ok, I'll just call that method on the main thread :/
