### ISSUE TITLE
NPE in ServerRequestQueue

### ISSUE THREAD

**Issue by Jeff11** [BranchMetrics/android-branch-deep-linking#512]
Got this from the crash logger. It happened just once on an S6 with Android 7.0.

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap$LinkedHashMapEntry java.util.LinkedHashMap$LinkedHashMapEntry.after' on a null object reference
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:416)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
at org.json.JSONObject.writeTo(JSONObject.java:719)
at org.json.JSONStringer.value(JSONStringer.java:237)
at org.json.JSONObject.writeTo(JSONObject.java:720)
at org.json.JSONStringer.value(JSONStringer.java:237)
at org.json.JSONArray.writeTo(JSONArray.java:613)
at org.json.JSONArray.toString(JSONArray.java:585)
at io.branch.referral.ServerRequestQueue$1.run(ServerRequestQueue.java:80)
at java.lang.Thread.run(Thread.java:762)`

**Comment by EvangelosG** [comment]
Thanks for your report @Jeff11 ! We'll take a look.

**Comment by sojanpr** [comment]
@Jeff11 We have opened a new PR for this issue https://github.com/BranchMetrics/android-branch-deep-linking/pull/513. Will de deployed with the next release

**Comment by TheCodeBender** [comment]
We are on 2.14.2 and also seeing a crash in ServerRequestQueue.java affecting about 300+ users.

**Comment by Jeff11** [comment]
Many more crashes are coming in, now at 150+

Please release a fix soon.

`Fatal Exception: java.lang.NullPointerException: Attempt to read from field 'java.util.LinkedHashMap$LinkedHashMapEntry java.util.LinkedHashMap$LinkedHashMapEntry.after' on a null object reference
       at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:416)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
       at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:430)
       at org.json.JSONObject.writeTo(JSONObject.java:719)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONObject.writeTo(JSONObject.java:720)
       at org.json.JSONStringer.value(JSONStringer.java:237)
       at org.json.JSONArray.writeTo(JSONArray.java:613)
       at org.json.JSONArray.toString(JSONArray.java:585)
       at io.branch.referral.ServerRequestQueue$1.run(ServerRequestQueue.java:78)
       at java.lang.Thread.run(Thread.java:762)`

**Comment by Jeff11** [comment]
Crashes happen on versions 2.12.1 - 2.14.2

**Comment by sojanpr** [comment]
@Jeff11 @TheCodeBender We are on this issue and release a fix soon

**Comment by sojanpr** [comment]
@Jeff11 @TheCodeBender  Added a fix to this PR https://github.com/BranchMetrics/android-branch-deep-linking/pull/520

Will be updating the SDK asap

**Comment by sojanpr** [comment]
@Jeff11 @TheCodeBender  Fix released with v2.14.3. Can you please try this version

**Comment by sojanpr** [comment]
A better fix for this issue is added to v2.14.4
