### ISSUE TITLE
Http connect exception: Handshake failed

### ISSUE THREAD

**Issue by elroid** [BranchMetrics/android-branch-deep-linking#552]
During certain situations, when trying to create a branch.io link using BranchShortLinkBuilder.generateShortUrl we are seeing the following error:

I/BranchRemoteInterfaceUrlConnection: Http connect exception: Handshake failed

which manifests itself as 

Url creation failed failed. Caused by(-113): Trouble creating a URL.  Branch API Error: poor network connectivity. Please try again later., responseCode=0

I've tracked it down to this location: https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/network/BranchRemoteInterfaceUrlConnection.java#L88

But it is unclear to me what url is failing. We are using a custom subdomain and we have recently had some SSL issues, so I was assuming this was the problem. However I've changed the branch config to use the standard riri.test-app.link and the issue has not gone away. Weirdly, it doesn't happen every time we generate it but is intermittent. Can you shed some light on what the issue might be?

**Comment by sojanpr** [comment]
@elroid Thanks for reaching out and filling in with the details. On further digging into the issue it seems like an `IOException` happening on the output stream writer here 
https://github.com/BranchMetrics/android-branch-deep-linking/blob/master/Branch-SDK/src/io/branch/referral/network/BranchRemoteInterfaceUrlConnection.java#L180

Do you know if this happens when  there is special or non UTF-8 characters present in the the link data?  We are looking into this and update you soon.

**Comment by elroid** [comment]
Any update on this? We're still completely stalled due to this issue. I'm unsure how to test what you suggest because I cannot see the data or url that is causing the issue from the log output of the compiled library (and both those exceptions output the same error message and swallow the stack trace), and I'm not having any luck getting my app working using this repo as a library project. I did manage to try using the included 2.16.0 jar but the problem persists. I then tried building the jar with some additional debug output but it's failing because it's unable to resolve https://repo1.maven.org/maven2/com/android/installreferrer/installreferrer/1.0/installreferrer-1.0.pom
Any suggestions would be appreciated.

**Comment by elroid** [comment]
Ok so I've managed to build the jar and used that to generate some more debug output. 

Here is output (with choice details redacted with "###") 
demonstrating the normal sequence of events, running on a Nexus 5 (OS 6.0.1): 

`I/BranchSDK(App): makeInviteUrl(uuid:EafTt)
I/BranchSDK(App): shortUrlBuilder.generateShortUrl()
I/BranchSDK: posting to https://api.branch.io/v1/url
I/BranchSDK: Post value = {"identity_id":"###","device_fingerprint_id":"###","session_id":"505009427385102556","tags":["invitation"],"data":"{\"InvitationID\":\"EafTt\",\"$always_deeplink\":\"true\",\"source\":\"android\"}","hardware_id":"########-####-####-####-############","is_hardware_id_real":false,"brand":"LGE","model":"Nexus 5","screen_dpi":480,"screen_height":1776,"screen_width":1080,"wifi":true,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":23,"country":"GB","language":"en","local_ip":"192.168.###.###","metadata":{},"instrumentation":{"v1\/url-qwt":"2","v1\/open-brtt":"275"},"sdk":"android2.16.2","branch_key":"key_test_###"}
I/BranchSDK: returned {"url":"https://riri.test-app.link/###"}
I/BranchSDK(App): shortUrlBuilder.onLinkCreate url:https://riri.test-app.link/###,error:null)`


And here is the same software (with added stack trace output) running on a Moto G (OS 5.1): 

`I/BranchSDK(App): makeInviteUrl(uuid:tBAXT)
I/BranchSDK(App): shortUrlBuilder.generateShortUrl()
I/BranchSDK: Branch Warning: You are using your test app's Branch Key. Remember to change it to live Branch Key during deployment.
I/BranchSDK: posting to https://api.branch.io/v1/open
I/BranchSDK: Post value = {"device_fingerprint_id":"###","identity_id":"###","hardware_id":"########-####-####-####-############","is_hardware_id_real":falcreen_height":1184,"screen_width":720,"wifi":true,"ui_mode":"UI_MODE_TYPE_NORMAL","os":"Android","os_version":22,"country":"GB","language":"en","local_ip":"192.168.###.###","app_version":"1.8.4-Alpha-DEBUG","facebook_app_link_checked":false,"is_referrable":1,"debug":true,"update":1,"latest_install_time":1521641963813,"latest_update_time":1521641963813,"first_install_time":1521641963813,"previous_update_time":1521641963813,"environment":"FULL_APP","cd":{"mv":"-1","pn":"###"},"metadata":{},"instrumentation":{"v1\/open-brtt":"121","v1\/open-qwt":"0"},"sdk":"android2.16.2","branch_key":"key_test_###"}
W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
W/System.err:     at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
W/System.err:     at com.android.okhttp.Connection.connect(Connection.java:155)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
W/System.err:     at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
W/System.err:     at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
W/System.err:     at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
W/System.err:     at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:136)
W/System.err:     at io.branch.referral.network.BranchRemoteInterfaceUrlConnection.doRestfulPost(BranchRemoteInterfaceUrlConnection.java:45)
W/System.err:     at io.branch.referral.network.BranchRemoteInterface.make_restful_post(BranchRemoteInterface.java:136)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:2736)
W/System.err:     at io.branch.referral.Branch$BranchPostTask.doInBackground(Branch.java:2714)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb7900440: Failure in SSL library, usually a protocol error
W/System.err: error:1407743E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert inappropriate fallback (external/openssl/ssl/s23_clnt.c:770 0xadedc005:0x00000000)
W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
W/System.err: 	... 19 more
I/BranchRemoteInterfaceUrlConnection: Http connect IOException(https://api.branch.io/v1/open): Handshake failed
I/BranchSDK(App): shortUrlBuilder.onLinkCreate url:https://riri.test-app.link?%24identity_id=###?tags=invitation&type=0&duration=0&source=android&data=###,error:BranchError[errorCode:-113,message:Trouble creating a URL.  Branch API Error: poor network connectivity. Please try again later.])`

The odd thing I've realised is that the two identical implementations are actually going through to different urls (the working one calling `api.branch.io/v1/url` and the failing one calling  `api.branch.io/v1/open`. Any idea why this might be happening? Let me know if you would like me to email you the full log output.

**Comment by sojanpr** [comment]
@elroid Thanks fro the details. Going  through it and let you know asap

**Comment by sojanpr** [comment]
@elroid Thanks for the detailed logs
The issue look like with SSL support on the device. Some of the Android 5.1 devices have a conflict SSL management leading to this issue.

` identical implementations are actually going through to different urls` 
  This behavior is correct. When SDK initialize it sends a `v1/open` request. Any other request will be send to Branch only if the  above is succeeded. In the cases  the `v1/open` request fails initially and  then it tries again when  there is a request for creating URL.

We are trying to reproduce this issue and working on a solution for disabling certificate validation.  Could you please help by providing the device name and os version.

Mean while you can try this following solution. Branch allows you to create your own custom network layer. Here are the steps
1) Extend you `CustomNetworkClass` class with `BranchRemoteInterface`
2) Implement abstract methods `doRestfulGet` `doRestfulPost`
3) Implement the rest calls with your favorite library (Volley , OkHttp  etc)
4) Call `Branch.getInstance().setBranchRemoteInterface(new CustomNetworkClass())` from your `Application.onCreate()` method.

**Comment by elroid** [comment]
Hi @sojanpr thanks for your suggestion. I will see if I can get it working using a custom networking class. The problematic device is a Moto G running 5.1 with security patch 2016-03-01.

**Comment by elroid** [comment]
@sojanpr Still struggling with this. Weirdly, it seems to only fail when i'm using our production server - the exact same app (sending the exact same data to the "open" call) works normally when using our dev environment. The only material difference between the two is that our dev server uses http and our prod server uses https. But I don't understand how that could make any difference - can you?

**Comment by sojanpr** [comment]
Thats really weird. Checked the scenario with a sample application and everything works fine. We may need more info on the app implementation to debug this issue. Can you please write to integrations@branch.io we can deal this issue there with more debigging

**Comment by elroid** [comment]
Ok I've managed to get things working by replacing the network interface, as you suggested. Still not quite sure why it was failing before, but it's working now so we're happy. FWIW, here's the networking class I created that did the trick: https://gist.github.com/elroid/b2137899f72c09d0b07aa8e3ede58499

Thanks for your help guys.
