### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: println needs a message

### ISSUE THREAD

**Issue by sw926** [BranchMetrics/android-branch-deep-linking#569]
Fatal Exception: java.lang.NullPointerException: println needs a message
       at android.util.Log.println_native(Log.java)
       at android.util.Log.i(Log.java:207)
       at io.branch.referral.PrefHelper.log(PrefHelper.java:1191)
       at io.branch.referral.PrefHelper.Debug(PrefHelper.java:1203)
       at io.branch.referral.InstallListener$ReferrerClientWrapper$1.onInstallReferrerSetupFinished(InstallListener.java:123)
       at com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected(InstallReferrerClientImpl.java:222)
       at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1101)
       at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1118)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5433)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by sojanpr** [comment]
@sw926 Thanks for the logs. Looks like InstallReferrer client is throwing exceptions with no messages. Added a protective shield  here 
https://github.com/BranchMetrics/android-branch-deep-linking/commit/018e4bf10a6d3671068d24f412cd3f90677f1476

Do you have `com.android.installreferrer` dependency added to your project by any chance?  it would really help us if you can update the version of above library  if used and the  OS version where you see this issue.
